# Generated by Django 5.2.9 on 2026-09-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0175_comun_telegram_ai_summary_prompt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=160)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PropertyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='explore.propertydefinition')),
            ],
            options={
                'ordering': ('property__position', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('element', 'Элемент'), ('community', 'Сообщество')], default='element', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('show_properties', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explore_node', to='feeds.comun')),
                ('properties', models.ManyToManyField(blank=True, related_name='nodes', to='explore.propertyoption')),
            ],
            options={
                'ordering': ('kind', 'title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='explore.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='explore.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='explore.node')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('source', 'target'), name='explore_unique_edge'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='explore_no_self_edge')],
            },
        ),
        migrations.AddConstraint(
            model_name='propertyoption',
            constraint=models.UniqueConstraint(fields=('property', 'value'), name='explore_unique_option'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('community__isnull', True), ('kind', 'element')), models.Q(('community__isnull', False), ('kind', 'community')), _connector='OR'), name='explore_node_kind_community'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'node'), name='explore_unique_subscription'),
        ),
    ]
