# Generated by Django 5.2.9 on 2026-01-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_post_comments_threading_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='force_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='shadow_banned',
            field=models.BooleanField(default=False),
        ),
    ]
