# Generated by Django 5.2.9 on 2026-01-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0023_author_force_home_author_shadow_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='value',
            field=models.SmallIntegerField(default=1),
        ),
    ]
