# Generated by Django 5.2.9 on 2026-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0050_siteuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='hide_from_fresh',
            field=models.BooleanField(default=False, help_text='Посты, созданные внутри этой комуны, не будут попадать в ленту Свежее.', verbose_name='Не показывать в свежем'),
        ),
        migrations.AddField(
            model_name='comun',
            name='hide_from_home',
            field=models.BooleanField(default=False, help_text='Посты, созданные внутри этой комуны, не будут попадать в Горячее.', verbose_name='Не показывать на главной'),
        ),
    ]
