# Generated by Django 5.2.9 on 2026-03-03 12:51

import feeds.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0055_comun_include_in_public_feeds_db_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="comun",
            name="allowed_post_templates",
            field=models.JSONField(
                blank=True,
                default=feeds.models.default_allowed_post_templates,
                help_text="Список типов шаблонов, разрешенных для публикаций внутри комуны.",
                verbose_name="Доступные шаблоны поста",
            ),
        ),
        migrations.AddField(
            model_name="rubric",
            name="allowed_post_templates",
            field=models.JSONField(
                blank=True,
                default=feeds.models.default_allowed_post_templates,
                help_text="Список типов шаблонов, разрешенных для публикаций в рубрике.",
                verbose_name="Доступные шаблоны поста",
            ),
        ),
    ]
