# Generated by Django 5.2.9 on 2026-03-03 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0056_post_template_allowlists"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sitenotification",
            new_name="feeds_siten_user_id_5d9dbf_idx",
            old_name="feeds_siteno_user_id_ca2769_idx",
        ),
        migrations.RenameIndex(
            model_name="sitenotification",
            new_name="feeds_siten_user_id_d075b9_idx",
            old_name="feeds_siteno_user_id_109bc3_idx",
        ),
        migrations.RenameIndex(
            model_name="sitenotification",
            new_name="feeds_siten_user_id_c1b295_idx",
            old_name="feeds_siteno_user_id_1be7a4_idx",
        ),
        migrations.RenameIndex(
            model_name="sitenotificationpreference",
            new_name="feeds_siten_user_id_4849c6_idx",
            old_name="feeds_siteno_user_id_aac9f6_idx",
        ),
    ]
