# Generated by Django 5.2.9 on 2026-03-03 14:35

from django.db import migrations, models


def create_default_template_configs(apps, schema_editor):
    PostTemplateConfig = apps.get_model("feeds", "PostTemplateConfig")
    default_blocks_by_template = {
        "basic": [],
        "movie_review": ["movie_time"],
    }
    existing_types = set(PostTemplateConfig.objects.values_list("template_type", flat=True))
    to_create = []
    for template_type, enabled_blocks in default_blocks_by_template.items():
        if template_type in existing_types:
            continue
        to_create.append(
            PostTemplateConfig(
                template_type=template_type,
                enabled_editor_blocks=enabled_blocks,
            )
        )
    if to_create:
        PostTemplateConfig.objects.bulk_create(to_create)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0057_rename_notification_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTemplateConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "template_type",
                    models.CharField(
                        choices=[("basic", "Базовый пост"), ("movie_review", "Кинообзор")],
                        max_length=32,
                        unique=True,
                        verbose_name="Тип шаблона",
                    ),
                ),
                (
                    "enabled_editor_blocks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Блоки редактора, которые можно использовать внутри шаблона.",
                        verbose_name="Доступные блоки редактора",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройка шаблона поста",
                "verbose_name_plural": "Настройки шаблонов постов",
                "ordering": ["template_type"],
            },
        ),
        migrations.RunPython(create_default_template_configs, noop_reverse),
    ]
