# Generated by Django 5.2.9 on 2026-03-04 13:10

from django.db import migrations


LEGACY_FULL_EDITOR_BLOCKS = [
    "header",
    "list",
    "image",
    "quote",
    "code",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "movie_time",
]

FULL_EDITOR_BLOCKS_WITH_MOVIE_CARD = [
    "header",
    "list",
    "image",
    "quote",
    "code",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "movie_time",
    "movie_card",
]


def _normalize_block_values(raw_value):
    if isinstance(raw_value, list):
        source = raw_value
    elif isinstance(raw_value, (tuple, set)):
        source = list(raw_value)
    elif isinstance(raw_value, str):
        source = [raw_value]
    else:
        source = []

    normalized = []
    seen = set()
    for item in source:
        value = str(item or "").strip().lower()
        if not value or value in seen:
            continue
        seen.add(value)
        normalized.append(value)
    return normalized


def backfill_movie_card_template_block(apps, schema_editor):
    PostTemplateConfig = apps.get_model("feeds", "PostTemplateConfig")
    for item in PostTemplateConfig.objects.all().iterator():
        template_type = str(item.template_type or "").strip().lower()
        if template_type != "movie_review":
            continue
        normalized_blocks = _normalize_block_values(item.enabled_editor_blocks)
        if normalized_blocks != LEGACY_FULL_EDITOR_BLOCKS:
            continue
        item.enabled_editor_blocks = list(FULL_EDITOR_BLOCKS_WITH_MOVIE_CARD)
        item.save(update_fields=["enabled_editor_blocks"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0059_backfill_template_editor_blocks"),
    ]

    operations = [
        migrations.RunPython(backfill_movie_card_template_block, noop_reverse),
    ]
