# Generated by Django 5.2.9 on 2026-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0060_backfill_movie_card_template_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplateconfig',
            name='template_type',
            field=models.CharField(choices=[('basic', 'Пост'), ('movie_review', 'Кинообзор'), ('post_vote_poll', 'Голосование за посты')], max_length=32, unique=True, verbose_name='Тип шаблона'),
        ),
    ]
