# Generated by Django 5.2.9 on 2026-03-05 07:05

from django.db import migrations


POST_VOTE_POLL_DEFAULT_BLOCKS = [
    "header",
    "list",
    "image",
    "quote",
    "code",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "movie_time",
]


def backfill_post_vote_poll_template_config(apps, schema_editor):
    PostTemplateConfig = apps.get_model("feeds", "PostTemplateConfig")
    PostTemplateConfig.objects.get_or_create(
        template_type="post_vote_poll",
        defaults={"enabled_editor_blocks": list(POST_VOTE_POLL_DEFAULT_BLOCKS)},
    )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0061_alter_posttemplateconfig_template_type"),
    ]

    operations = [
        migrations.RunPython(backfill_post_vote_poll_template_config, noop_reverse),
    ]
