# Generated by Django 5.2.9 on 2026-03-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0062_backfill_post_vote_poll_template_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="rubric",
            name="allow_for_telegram_channel",
            field=models.BooleanField(
                default=True,
                help_text="Если выключено, рубрика не будет доступна для выбора в настройках Telegram-бота.",
                verbose_name="Можно выбрать рубрикой для телеграм канала",
            ),
        ),
    ]
