# Generated by Django 5.2.9 on 2026-03-05 13:30

from django.db import migrations, models


MUSIC_RELEASE_DEFAULT_BLOCKS = [
    "header",
    "list",
    "image",
    "quote",
    "code",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "music",
    "movie_time",
]


def create_music_release_template_config(apps, schema_editor):
    PostTemplateConfig = apps.get_model("feeds", "PostTemplateConfig")
    PostTemplateConfig.objects.get_or_create(
        template_type="music_release",
        defaults={"enabled_editor_blocks": list(MUSIC_RELEASE_DEFAULT_BLOCKS)},
    )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0064_backfill_music_template_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posttemplateconfig",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("basic", "Пост"),
                    ("movie_review", "Кинообзор"),
                    ("post_vote_poll", "Голосование за посты"),
                    ("music_release", "Музыкальный релиз"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Тип шаблона",
            ),
        ),
        migrations.RunPython(create_music_release_template_config, noop_reverse),
    ]
