# Generated by Django 5.2.9 on 2026-03-05 18:05

from django.db import migrations


LEGACY_BASIC_BLOCKS = [
    "header",
    "list",
    "image",
    "quote",
    "code",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "music",
    "movie_time",
]

LEGACY_MOVIE_REVIEW_BLOCKS = [
    "header",
    "list",
    "image",
    "quote",
    "code",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "music",
    "movie_time",
    "movie_card",
]

BLOCKS_WITH_SPOILER_BASIC = [
    "header",
    "list",
    "image",
    "quote",
    "code",
    "spoiler",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "music",
    "movie_time",
]

BLOCKS_WITH_SPOILER_MOVIE_REVIEW = [
    "header",
    "list",
    "image",
    "quote",
    "code",
    "spoiler",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "music",
    "movie_time",
    "movie_card",
]

BLOCKS_WITH_SPOILER_BY_TEMPLATE = {
    "basic": BLOCKS_WITH_SPOILER_BASIC,
    "post_vote_poll": BLOCKS_WITH_SPOILER_BASIC,
    "music_release": BLOCKS_WITH_SPOILER_BASIC,
    "movie_review": BLOCKS_WITH_SPOILER_MOVIE_REVIEW,
}

LEGACY_BLOCKS_BY_TEMPLATE = {
    "basic": LEGACY_BASIC_BLOCKS,
    "post_vote_poll": LEGACY_BASIC_BLOCKS,
    "music_release": LEGACY_BASIC_BLOCKS,
    "movie_review": LEGACY_MOVIE_REVIEW_BLOCKS,
}


def _normalize_block_values(raw_value):
    if isinstance(raw_value, list):
        source = raw_value
    elif isinstance(raw_value, (tuple, set)):
        source = list(raw_value)
    elif isinstance(raw_value, str):
        source = [raw_value]
    else:
        source = []

    normalized = []
    seen = set()
    for item in source:
        value = str(item or "").strip().lower()
        if not value or value in seen:
            continue
        seen.add(value)
        normalized.append(value)
    return normalized


def backfill_spoiler_template_block(apps, schema_editor):
    PostTemplateConfig = apps.get_model("feeds", "PostTemplateConfig")
    for item in PostTemplateConfig.objects.all().iterator():
        template_type = str(item.template_type or "").strip().lower()
        legacy_blocks = LEGACY_BLOCKS_BY_TEMPLATE.get(template_type)
        if not legacy_blocks:
            continue
        normalized_blocks = _normalize_block_values(item.enabled_editor_blocks)
        if normalized_blocks != legacy_blocks:
            continue
        item.enabled_editor_blocks = list(BLOCKS_WITH_SPOILER_BY_TEMPLATE[template_type])
        item.save(update_fields=["enabled_editor_blocks"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0065_add_music_release_template_type"),
    ]

    operations = [
        migrations.RunPython(backfill_spoiler_template_block, noop_reverse),
    ]
