# Generated by Django 5.2.9 on 2026-03-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0072_backfill_post_rating_template_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="comun",
            name="minimum_author_rating_to_post",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Если больше нуля, писать в коммуну смогут только авторы с указанным рейтингом или выше.",
                max_digits=8,
                verbose_name="Минимальный рейтинг автора для публикации",
            ),
        ),
    ]
