# Generated by Django 5.2.9 on 2026-03-15 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0073_comun_minimum_author_rating_to_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRatingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('post_like', 'Лайк поста'), ('comment_like', 'Лайк комментария')], max_length=32)),
                ('delta', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_rating_events', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_events', to='feeds.author')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_rating_events', to='feeds.postcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_rating_events', to='feeds.post')),
            ],
            options={
                'verbose_name': 'Изменение рейтинга автора',
                'verbose_name_plural': 'Изменения рейтинга авторов',
                'indexes': [models.Index(fields=['author', 'created_at'], name='feeds_autho_author__f0a667_idx'), models.Index(fields=['created_at'], name='feeds_autho_created_8ab90f_idx')],
            },
        ),
    ]
