# Generated by Django 5.2.9 on 2026-04-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0088_comun_telegram_channel_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='glossary_enabled',
            field=models.BooleanField(default=False, help_text='Если включено, в сообществе будет доступна публичная страница глоссария и вставка терминов в публикации.', verbose_name='Включить глоссарий'),
        ),
        migrations.CreateModel(
            name='ComunGlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=180, verbose_name='Термин')),
                ('slug', models.SlugField(max_length=180, verbose_name='Slug термина')),
                ('definition', models.TextField(blank=True, verbose_name='Расшифровка')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='feeds.comun', verbose_name='Сообщество')),
            ],
            options={
                'verbose_name': 'Термин глоссария сообщества',
                'verbose_name_plural': 'Термины глоссария сообществ',
                'ordering': ['sort_order', 'term'],
                'constraints': [models.UniqueConstraint(fields=('comun', 'slug'), name='feeds_unique_comun_glossary_term_slug_per_comun'), models.UniqueConstraint(fields=('comun', 'term'), name='feeds_unique_comun_glossary_term_name_per_comun')],
            },
        ),
    ]
