# Generated by Django 5.2.9 on 2026-04-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0093_comuncustomposttemplate_and_more'),
        ('feeds', '0094_push_notifications'),
    ]

    operations = [
    ]
