# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0095_merge_20260424_0718"),
    ]

    operations = [
        migrations.AddField(
            model_name="comuncustomposttemplatefield",
            name="settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="Настройки поля"),
        ),
    ]
