# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0098_dynamic_custom_post_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="comun",
            name="roadmap_category_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="ID внутренних категорий сообщества, публикации из которых попадают в дорожную карту.",
                verbose_name="Категории дорожной карты",
            ),
        ),
    ]
