# Generated by Codex on 2026-05-06

from django.db import migrations, models


def disable_default_roadmap(apps, schema_editor):
    Comun = apps.get_model("feeds", "Comun")
    Comun.objects.filter(roadmap_enabled=True).update(roadmap_enabled=False)


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0102_reassign_comuna_posts_to_personal_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comun",
            name="roadmap_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, в сообществе будет доступна публичная дорожная карта.",
                verbose_name="Включить дорожную карту",
            ),
        ),
        migrations.RunPython(disable_default_roadmap, migrations.RunPython.noop),
    ]
