# Generated by Codex on 2026-05-06

import re

from django.db import migrations, models
from django.db.models import Q
from django.utils.text import slugify


def normalize_telegram_username(value: object) -> str:
    username = str(value or "").strip().lstrip("@")
    if not username:
        return ""
    return re.sub(r"\s+", "", username).lower()


def unique_name(Comun, base_name: str, fallback: str) -> str:
    normalized = re.sub(r"\s+", " ", str(base_name or "").strip())
    if not normalized:
        normalized = f"@{fallback}"
    candidate = normalized[:160]
    suffix = 2
    while Comun.objects.filter(name__iexact=candidate).exists():
        suffix_literal = f" {suffix}"
        max_base_length = max(160 - len(suffix_literal), 1)
        candidate = f"{normalized[:max_base_length]}{suffix_literal}"
        suffix += 1
    return candidate


def unique_slug(Comun, base_slug: str, fallback_id: int) -> str:
    normalized = slugify(str(base_slug or "").strip(), allow_unicode=False)
    if not normalized:
        normalized = f"channel-{fallback_id}"
    normalized = normalized[:150]
    candidate = normalized
    suffix = 2
    while Comun.objects.filter(slug=candidate).exists():
        suffix_literal = f"-{suffix}"
        max_base_length = max(160 - len(suffix_literal), 1)
        candidate = f"{normalized[:max_base_length]}{suffix_literal}"
        suffix += 1
    return candidate


def first_verified_owner_id(AuthorAdmin, author_id: int) -> int | None:
    return (
        AuthorAdmin.objects.filter(author_id=author_id, verified_at__isnull=False)
        .order_by("verified_at", "created_at", "id")
        .values_list("user_id", flat=True)
        .first()
    )


def backfill_channel_comuns(apps, schema_editor):
    Author = apps.get_model("feeds", "Author")
    AuthorAdmin = apps.get_model("feeds", "AuthorAdmin")
    Comun = apps.get_model("feeds", "Comun")

    channel_authors = (
        Author.objects.filter(is_blocked=False)
        .filter(Q(channel_id__isnull=False) | ~Q(channel_url="") | ~Q(invite_url=""))
        .order_by("id")
    )

    for author in channel_authors.iterator():
        username = normalize_telegram_username(author.username)
        if not username:
            continue
        if Comun.objects.filter(telegram_source_author_id=author.id).exists():
            continue

        owner_id = first_verified_owner_id(AuthorAdmin, author.id)
        comun = (
            Comun.objects.filter(
                telegram_channel_username__iexact=username,
                telegram_source_author__isnull=True,
                is_active=True,
            )
            .order_by("id")
            .first()
        )

        if comun:
            update_fields = ["telegram_source_author", "telegram_channel_username", "updated_at"]
            comun.telegram_source_author_id = author.id
            comun.telegram_channel_username = username
            if owner_id and not comun.creator_id:
                comun.creator_id = owner_id
                update_fields.append("creator")
            comun.save(update_fields=update_fields)
        else:
            comun = Comun.objects.create(
                name=unique_name(Comun, author.title, username),
                slug=unique_slug(Comun, username, author.id),
                creator_id=owner_id,
                logo_url=author.avatar_url or "",
                product_description=(author.description or "").strip(),
                telegram_source_author_id=author.id,
                telegram_channel_username=username,
            )

        if owner_id:
            comun.moderators.add(owner_id)


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0103_comun_roadmap_disabled_by_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comun",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="created_comuns",
                to="auth.user",
                verbose_name="Создатель",
            ),
        ),
        migrations.RunPython(backfill_channel_comuns, migrations.RunPython.noop),
    ]
