# Generated by Codex on 2026-05-06

from django.conf import settings
from django.db import migrations


def author_avatar_logo_url(author) -> str:
    avatar_image = getattr(author, "avatar_image", None)
    if avatar_image:
        try:
            image_url = avatar_image.url
        except Exception:
            image_url = ""
        if image_url:
            site_base = getattr(settings, "SITE_BASE_URL", "").rstrip("/")
            if site_base and image_url.startswith("/"):
                image_url = f"{site_base}{image_url}"
            return image_url[:500]
    return str(getattr(author, "avatar_url", "") or "").strip()[:500]


def backfill_channel_comun_logos(apps, schema_editor):
    Comun = apps.get_model("feeds", "Comun")

    queryset = (
        Comun.objects.select_related("telegram_source_author")
        .filter(
            is_active=True,
            telegram_source_author__isnull=False,
        )
        .order_by("id")
    )

    for comun in queryset.iterator():
        author = comun.telegram_source_author
        logo_url = author_avatar_logo_url(author)
        if not logo_url or comun.logo_url == logo_url:
            continue
        current_logo_url = str(comun.logo_url or "").strip()
        if current_logo_url:
            generated_avatar_logo = (
                "api.telegram.org/file/" in current_logo_url
                or "/media/authors/avatars/" in current_logo_url
                or current_logo_url == str(getattr(author, "avatar_url", "") or "").strip()
            )
            if not generated_avatar_logo:
                continue
        comun.logo_url = logo_url
        comun.save(update_fields=["logo_url"])


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0104_backfill_channel_comuns"),
    ]

    operations = [
        migrations.RunPython(backfill_channel_comun_logos, migrations.RunPython.noop),
    ]
