# Generated by Codex on 2026-05-06

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models
from django.db.models import Q, Sum
from django.utils import timezone


COMMENT_RATING_WEIGHT = Decimal("0.1")


def _comun_rating_value(post_rating_total, comments_total) -> Decimal:
    score = Decimal(int(post_rating_total or 0)) + (
        Decimal(int(comments_total or 0)) * COMMENT_RATING_WEIGHT
    )
    return score.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def _publish_ready_filter(now):
    return Q(publish_at__isnull=True) | Q(publish_at__lte=now)


def _comun_posts_queryset(Post, comun, now):
    membership_filter = Q()
    has_source = False

    source_tag_ids = set()
    product_tag_id = getattr(comun, "product_tag_id", None)
    if product_tag_id:
        source_tag_ids.add(product_tag_id)
    try:
        source_tag_ids.update(
            comun.source_tags.filter(is_active=True).values_list("id", flat=True)
        )
    except Exception:
        pass
    if source_tag_ids:
        membership_filter |= Q(tags__id__in=list(source_tag_ids))
        has_source = True

    source_rubric_id = getattr(comun, "source_rubric_id", None)
    if source_rubric_id:
        membership_filter |= Q(rubric_id=source_rubric_id)
        has_source = True

    telegram_source_author_id = getattr(comun, "telegram_source_author_id", None)
    if telegram_source_author_id:
        membership_filter |= Q(author_id=telegram_source_author_id)
        has_source = True

    comun_slug = str(getattr(comun, "slug", "") or "").strip()
    if comun_slug:
        membership_filter |= Q(raw_data__source="manual_comun", raw_data__comun_slug=comun_slug)
        has_source = True

    if not has_source:
        return Post.objects.none()

    queryset = (
        Post.objects.filter(
            membership_filter,
            is_blocked=False,
            is_pending=False,
            author__is_blocked=False,
        )
        .filter(_publish_ready_filter(now))
        .distinct()
    )

    channel_author_filter = (
        Q(author__channel_id__isnull=False)
        | Q(author__channel_url__gt="")
        | Q(author__invite_url__gt="")
    )
    if telegram_source_author_id:
        queryset = queryset.exclude(channel_author_filter & ~Q(author_id=telegram_source_author_id))
    else:
        queryset = queryset.exclude(channel_author_filter)

    try:
        excluded_author_ids = list(comun.excluded_authors.values_list("id", flat=True))
    except Exception:
        excluded_author_ids = []
    if excluded_author_ids:
        queryset = queryset.exclude(author_id__in=excluded_author_ids)

    try:
        blocked_tag_ids = list(comun.blocked_tags.filter(is_active=True).values_list("id", flat=True))
    except Exception:
        blocked_tag_ids = []
    if blocked_tag_ids:
        queryset = queryset.exclude(tags__id__in=blocked_tag_ids).distinct()

    return queryset


def backfill_comun_rating_from_posts(apps, schema_editor):
    Comun = apps.get_model("feeds", "Comun")
    Post = apps.get_model("feeds", "Post")

    now = timezone.now()
    for comun in (
        Comun.objects.filter(is_active=True)
        .prefetch_related("source_tags", "excluded_authors", "blocked_tags")
        .order_by("id")
        .iterator(chunk_size=100)
    ):
        totals = _comun_posts_queryset(Post, comun, now).aggregate(
            post_rating_total=Sum("rating"),
            comments_total=Sum("comments_count"),
        )
        comun.rating_score = _comun_rating_value(
            totals.get("post_rating_total"),
            totals.get("comments_total"),
        )
        comun.save(update_fields=["rating_score"])


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0105_backfill_channel_comun_logos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comun",
            name="rating_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Рейтинг",
            ),
        ),
        migrations.RunPython(backfill_comun_rating_from_posts, migrations.RunPython.noop),
    ]
