# Generated by Django 5.2.9 on 2026-05-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0117_public_feed_item'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobilepushdevice',
            new_name='feeds_mobil_user_id_6bb55c_idx',
            old_name='feeds_mobile_user_id_680b49_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilepushdevice',
            new_name='feeds_mobil_user_id_c60b86_idx',
            old_name='feeds_mobile_user_id_94bb37_idx',
        ),
        migrations.RenameIndex(
            model_name='mobilepushdevice',
            new_name='feeds_mobil_user_id_3569c1_idx',
            old_name='feeds_mobile_user_id_9a5736_idx',
        ),
        migrations.RenameIndex(
            model_name='sitenotification',
            new_name='feeds_siten_user_id_c2aa50_idx',
            old_name='feeds_siteno_user_id_c6eaa2_idx',
        ),
        migrations.AlterField(
            model_name='comuncustomposttemplateblock',
            name='block_type',
            field=models.CharField(choices=[('toc', 'Оглавление'), ('header', 'Заголовок'), ('list', 'Список'), ('table', 'Таблица'), ('image', 'Изображение'), ('quote', 'Цитата'), ('callout', 'Врезка'), ('author', 'Автор'), ('code', 'Код'), ('poll', 'Опрос'), ('divider', 'Разделитель'), ('spoiler', 'Спойлер'), ('gallery', 'Галерея'), ('map', 'Карта'), ('compare', 'Сравнение изображений'), ('link', 'Ссылка'), ('embed', 'Встраивание (Embed)'), ('post_link', 'Ссылка на пост'), ('music', 'Музыка'), ('movie_time', 'Время в фильме'), ('movie_card', 'Карточка фильма'), ('post_rating', 'Рейтинг')], max_length=64, verbose_name='Блок редактора'),
        ),
        migrations.AlterField(
            model_name='comuncustomposttemplatefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('select', 'Выбор значений'), ('checkbox', 'Чекбокс')], default='text', max_length=16, verbose_name='Тип поля'),
        ),
    ]
