# Generated by Django 5.2.9 on 2026-05-12 14:34

from django.db import migrations, models


def backfill_post_previews(apps, schema_editor):
    from feeds.preview import build_post_preview

    Post = apps.get_model("feeds", "Post")
    batch: list[Post] = []
    for post in Post.objects.only("id", "content", "raw_data").iterator(chunk_size=1000):
        preview = build_post_preview(post.content or "", post.raw_data)
        post.preview_content = preview["preview_content"]
        post.preview_image_url = preview["preview_image_url"]
        batch.append(post)
        if len(batch) >= 1000:
            Post.objects.bulk_update(batch, ["preview_content", "preview_image_url"])
            batch.clear()
    if batch:
        Post.objects.bulk_update(batch, ["preview_content", "preview_image_url"])


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0118_rename_feeds_mobile_user_id_680b49_idx_feeds_mobil_user_id_6bb55c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_image_url',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(backfill_post_previews, migrations.RunPython.noop),
    ]
