# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0122_rebuild_previews_after_orphan_image_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttemplateconfig",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Неактивный шаблон скрыт из выбора и не применяется к постам.",
                verbose_name="Активен",
            ),
        ),
    ]
