# Generated by Codex on 2026-05-13

from django.db import migrations


BUG_REPORT_ENABLED_EDITOR_BLOCKS = [
    "toc",
    "header",
    "list",
    "table",
    "image",
    "quote",
    "callout",
    "author",
    "code",
    "poll",
    "divider",
    "spoiler",
    "gallery",
    "map",
    "compare",
    "link",
    "embed",
    "post_link",
    "music",
    "movie_time",
    "post_rating",
]


def create_bug_report_template_config(apps, schema_editor):
    PostTemplateConfig = apps.get_model("feeds", "PostTemplateConfig")
    config, created = PostTemplateConfig.objects.get_or_create(
        template_type="bug_report",
        defaults={
            "label": "Баг-репорт",
            "description": "Статус, платформа, браузер, код ошибки и скриншот.",
            "enabled_editor_blocks": BUG_REPORT_ENABLED_EDITOR_BLOCKS,
            "is_active": True,
        },
    )
    if created:
        return
    config.label = config.label or "Баг-репорт"
    config.description = config.description or "Статус, платформа, браузер, код ошибки и скриншот."
    if not config.enabled_editor_blocks:
        config.enabled_editor_blocks = BUG_REPORT_ENABLED_EDITOR_BLOCKS
    config.is_active = True
    config.save(
        update_fields=["label", "description", "enabled_editor_blocks", "is_active", "updated_at"]
    )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0123_posttemplateconfig_is_active"),
    ]

    operations = [
        migrations.RunPython(create_bug_report_template_config, noop_reverse),
    ]
