# Generated by Codex on 2026-05-15

from django.db import migrations, models


def restrict_channel_comuns_to_team(apps, schema_editor):
    Comun = apps.get_model("feeds", "Comun")
    Comun.objects.filter(
        telegram_source_author__isnull=False,
        only_moderators_can_post=False,
    ).update(only_moderators_can_post=True)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0127_post_bug_report_confirmation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comun",
            name="only_moderators_can_post",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, писать в коммуну смогут только ее создатель и модераторы.",
                verbose_name="Публикация только для создателя и модераторов",
            ),
        ),
        migrations.AlterField(
            model_name="comuncategory",
            name="only_moderators_can_post",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, писать в эту категорию смогут только создатель сообщества и модераторы.",
                verbose_name="Публикация только для создателя и модераторов",
            ),
        ),
        migrations.RunPython(restrict_channel_comuns_to_team, noop_reverse),
    ]
