# Generated by Codex on 2026-05-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feeds", "0130_notification_grouping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comun",
            name="knowledge_base_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, в сообществе будет доступна публичная база знаний из отмеченных постов.",
                verbose_name="Включить базу знаний",
            ),
        ),
        migrations.CreateModel(
            name="ComunKnowledgeBaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("group", "Группа"), ("post", "Пост")],
                        default="post",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_base_items",
                        to="feeds.comun",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_comun_knowledge_base_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="feeds.comunknowledgebaseitem",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_base_items",
                        to="feeds.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент базы знаний",
                "verbose_name_plural": "База знаний сообществ",
                "ordering": ["sort_order", "title", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="comunknowledgebaseitem",
            index=models.Index(fields=["comun", "parent", "sort_order"], name="comun_kb_tree_idx"),
        ),
        migrations.AddIndex(
            model_name="comunknowledgebaseitem",
            index=models.Index(fields=["post"], name="comun_kb_post_idx"),
        ),
        migrations.AddConstraint(
            model_name="comunknowledgebaseitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(post__isnull=False),
                fields=("comun", "post"),
                name="comun_kb_unique_post",
            ),
        ),
    ]
