# Generated by Django 5.2.9 on 2026-05-20 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0132_botsession_verified_user_id_channel_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuserprofile',
            name='registration_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteuserprofile',
            name='registration_source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='siteuserprofile',
            index=models.Index(fields=['registration_source'], name='feeds_siteu_regsrc_8f2c4d_idx'),
        ),
    ]
