# Generated by Django 5.2.9 on 2026-06-09 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0136_restore_cumulative_comun_ratings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_chats_as_user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_chats_as_user_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чат пользователей',
                'verbose_name_plural': 'Чаты пользователей',
            },
        ),
        migrations.CreateModel(
            name='SiteChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='feeds.sitechat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_site_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чатов',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='sitechat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='feeds.sitechatmessage'),
        ),
        migrations.AddIndex(
            model_name='sitechat',
            index=models.Index(fields=['user_one', 'last_message_at'], name='feeds_sitec_userone_c5c20d_idx'),
        ),
        migrations.AddIndex(
            model_name='sitechat',
            index=models.Index(fields=['user_two', 'last_message_at'], name='feeds_sitec_usertwo_2c8d87_idx'),
        ),
        migrations.AddIndex(
            model_name='sitechat',
            index=models.Index(fields=['last_message_at'], name='feeds_sitec_lastmsg_963d17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sitechat',
            unique_together={('user_one', 'user_two')},
        ),
        migrations.AddIndex(
            model_name='sitechatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='feeds_sitec_chat_cr_358d84_idx'),
        ),
        migrations.AddIndex(
            model_name='sitechatmessage',
            index=models.Index(fields=['chat', 'sender', 'read_at'], name='feeds_sitec_chat_se_241934_idx'),
        ),
        migrations.AddIndex(
            model_name='sitechatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='feeds_sitec_sender__2862b3_idx'),
        ),
    ]
