# Generated by Django 5.2.9 on 2026-06-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0140_comun_glossary_auto_link_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Группа или супергруппа Telegram, из которой можно предлагать материалы в базу знаний и глоссарий.', null=True, unique=True, verbose_name='ID Telegram-чата'),
        ),
        migrations.AddField(
            model_name='comun',
            name='telegram_chat_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название Telegram-чата'),
        ),
        migrations.CreateModel(
            name='ComunTelegramSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('knowledge_base', 'База знаний'), ('glossary', 'Глоссарий')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('telegram_chat_id', models.BigIntegerField()),
                ('telegram_chat_title', models.CharField(blank=True, max_length=255)),
                ('telegram_source_message_id', models.BigIntegerField()),
                ('telegram_request_message_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_source_url', models.URLField(blank=True, max_length=500)),
                ('source_author_name', models.CharField(blank=True, max_length=255)),
                ('source_text', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('glossary_term', models.CharField(blank=True, max_length=180)),
                ('glossary_definition', models.TextField(blank=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_submissions', to='feeds.comun', verbose_name='Сообщество')),
                ('created_glossary_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_submissions', to='feeds.comunglossaryterm')),
                ('created_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_knowledge_base_submissions', to='feeds.post')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comun_telegram_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Предложил пользователь')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_comun_telegram_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Проверил пользователь')),
            ],
            options={
                'verbose_name': 'Telegram-заявка сообщества',
                'verbose_name_plural': 'Telegram-заявки сообществ',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['comun', 'status', '-created_at'], name='comtgsub_comun_status_idx'), models.Index(fields=['telegram_chat_id', 'telegram_source_message_id'], name='comtgsub_tg_msg_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('comun', 'request_type', 'telegram_chat_id', 'telegram_source_message_id'), name='comtgsub_unique_pending_source')],
            },
        ),
    ]
