# Generated by Django 5.2.9 on 2026-06-24 06:09

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0141_comun_telegram_chat_id_comun_telegram_chat_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunglossaryterm',
            name='image',
            field=models.ImageField(blank=True, upload_to=communities.models.comun_glossary_image_path, verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='comunglossaryterm',
            name='term_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='Термин на английском'),
        ),
    ]
