# Generated by Django 5.2.9 on 2026-06-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0142_comunglossaryterm_image_comunglossaryterm_term_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('tr', 'Турецкий'), ('id', 'Индонезийский')], db_index=True, max_length=8)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('preview_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('translated', 'Переведен'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='feeds.post')),
            ],
            options={
                'verbose_name': 'Перевод поста',
                'verbose_name_plural': 'Переводы постов',
                'ordering': ['post_id', 'language'],
                'indexes': [models.Index(fields=['language', 'status'], name='post_trans_lang_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'language'), name='unique_post_translation_language')],
            },
        ),
    ]
