# Generated by Django 5.2.9 on 2026-06-29 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0144_movie_review_release_date_to_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunSubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comun_slug', models.SlugField(max_length=120)),
                ('source', models.CharField(choices=[('feed_settings', 'Настройки ленты'), ('moderator_sync', 'Автоподписка модератора')], default='feed_settings', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to='feeds.comun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comun_subscription_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие подписки на сообщество',
                'verbose_name_plural': 'События подписок на сообщества',
                'indexes': [models.Index(fields=['created_at'], name='feeds_comsub_created_idx'), models.Index(fields=['comun', 'created_at'], name='feeds_comsub_comun_created_idx'), models.Index(fields=['user', 'created_at'], name='feeds_comsub_user_created_idx')],
            },
        ),
    ]
