# Generated by Django 5.2.9 on 2026-06-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0145_comun_subscription_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_views_target_min', models.PositiveIntegerField(default=30)),
                ('fake_views_target_max', models.PositiveIntegerField(default=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки просмотров',
                'verbose_name_plural': 'Настройки просмотров',
            },
        ),
    ]
