# Generated by Django 5.2.9 on 2026-06-29 19:09

from django.conf import settings
from django.db import migrations, models


def mark_existing_notifications_delivered(apps, schema_editor):
    SiteNotification = apps.get_model('feeds', 'SiteNotification')
    SiteNotification.objects.filter(delivered_at__isnull=True).update(
        delivery_at=models.F('created_at'),
        delivered_at=models.F('created_at'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0146_post_view_settings_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenotification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitenotification',
            name='delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_notifications_delivered, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='sitenotification',
            index=models.Index(fields=['delivered_at', 'delivery_at'], name='feeds_siten_deliver_983b92_idx'),
        ),
    ]
