# Generated by Django 5.2.9 on 2026-07-01 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0151_content_translation_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTranslationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('post_daily_limit', models.PositiveIntegerField(default=200)),
                ('comment_daily_limit', models.PositiveIntegerField(default=1000)),
                ('post_object_daily_limit', models.PositiveIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки перевода контента',
                'verbose_name_plural': 'Настройки перевода контента',
            },
        ),
        migrations.CreateModel(
            name='ContentTranslationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post', 'Пост'), ('comment', 'Комментарий'), ('comun', 'Сообщество')], max_length=16)),
                ('object_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='feeds.contenttranslationtask')),
            ],
            options={
                'verbose_name': 'Запуск перевода контента',
                'verbose_name_plural': 'Запуски перевода контента',
                'indexes': [models.Index(fields=['kind', 'created_at'], name='content_trans_run_kind_day_idx'), models.Index(fields=['kind', 'object_id', 'created_at'], name='content_trans_run_obj_day_idx')],
            },
        ),
    ]
