# Generated by Django 5.2.9 on 2026-07-07 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0157_comuntranslation_extended_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttranslationrun',
            name='kind',
            field=models.CharField(choices=[('post', 'Пост'), ('comment', 'Комментарий'), ('comun', 'Сообщество'), ('static_page', 'Статичная страница')], max_length=16),
        ),
        migrations.AlterField(
            model_name='contenttranslationtask',
            name='kind',
            field=models.CharField(choices=[('post', 'Пост'), ('comment', 'Комментарий'), ('comun', 'Сообщество'), ('static_page', 'Статичная страница')], max_length=16),
        ),
        migrations.CreateModel(
            name='StaticPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'Английский'), ('es', 'Испанский'), ('pt', 'Португальский'), ('de', 'Немецкий'), ('fr', 'Французский'), ('tr', 'Турецкий'), ('id', 'Индонезийский')], db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('translated', 'Переведен'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('content', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('error_message', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='feeds.staticpagecontent')),
            ],
            options={
                'verbose_name': 'Перевод статичной страницы',
                'verbose_name_plural': 'Переводы статичных страниц',
                'ordering': ['page_id', 'language'],
                'indexes': [models.Index(fields=['language', 'status'], name='static_page_tr_lang_st_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'language'), name='unique_static_page_translation_language')],
            },
        ),
    ]
