# Generated by Django 5.2.9 on 2026-07-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0158_alter_contenttranslationrun_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedsettings',
            name='interface_language_manual',
            field=models.BooleanField(default=False),
        ),
    ]
