# Generated by Codex on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0161_socialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="comun",
            name="community_map_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, в сообществе будет доступна публичная карта с GPS-метками из публикаций.",
                verbose_name="Включить общую карту",
            ),
        ),
        migrations.CreateModel(
            name="ComunMapPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_index", models.PositiveIntegerField(default=0, verbose_name="Индекс блока")),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9, verbose_name="Широта")),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9, verbose_name="Долгота")),
                ("zoom", models.PositiveSmallIntegerField(default=14, verbose_name="Масштаб")),
                ("raw", models.CharField(blank=True, max_length=255, verbose_name="Исходная строка")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_points",
                        to="feeds.comun",
                        verbose_name="Сообщество",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comun_map_points",
                        to="feeds.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка общей карты",
                "verbose_name_plural": "Точки общих карт",
                "ordering": ["-post__created_at", "post_id", "block_index", "id"],
                "indexes": [
                    models.Index(fields=["comun", "post"], name="comun_map_comun_post_idx"),
                    models.Index(fields=["post"], name="comun_map_post_idx"),
                    models.Index(fields=["lat", "lng"], name="comun_map_lat_lng_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "block_index"),
                        name="comun_map_point_unique_post_block",
                    ),
                ],
            },
        ),
    ]
