# Generated by Django 5.2.9 on 2026-07-17 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0162_comun_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', 'Пост'), ('comment', 'Комментарий')], max_length=16)),
                ('reason', models.CharField(choices=[('sexualized', 'Сексуализированный контент'), ('illegal', 'Незаконный контент'), ('harassment', 'Травля'), ('spam_fraud', 'Спам, мошенничество'), ('other', 'Иное')], max_length=32)),
                ('title_snapshot', models.CharField(blank=True, max_length=255)),
                ('content_snapshot', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Новая'), ('reviewed', 'Обработана'), ('dismissed', 'Отклонена')], db_index=True, default='open', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to='feeds.postcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to='feeds.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жалоба на контент',
                'verbose_name_plural': 'Жалобы на контент',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='content_report_status_idx'), models.Index(fields=['target_type', '-created_at'], name='content_report_target_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False), ('target_type', 'post')), models.Q(('comment__isnull', False), ('post__isnull', True), ('target_type', 'comment')), _connector='OR'), name='content_report_has_one_target'), models.UniqueConstraint(condition=models.Q(('target_type', 'post')), fields=('reporter', 'post'), name='unique_reporter_post_report'), models.UniqueConstraint(condition=models.Q(('target_type', 'comment')), fields=('reporter', 'comment'), name='unique_reporter_comment_report')],
            },
        ),
    ]
