# Generated by Django 5.2.9 on 2026-07-20 07:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0166_draftblockcommentthread_draftblockcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='analytics_tracking_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comunsubscriptionevent',
            name='action',
            field=models.CharField(choices=[('subscribe', 'Подписка'), ('unsubscribe', 'Отписка')], default='subscribe', max_length=16),
        ),
        migrations.CreateModel(
            name='PostDailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='feeds.post')),
            ],
            options={
                'verbose_name': 'Просмотры поста за день',
                'verbose_name_plural': 'Просмотры постов по дням',
                'indexes': [models.Index(fields=['date'], name='postdailyview_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'date'), name='feeds_post_daily_view_unique')],
            },
        ),
    ]
