# Generated by Codex on 2026-07-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0167_comun_analytics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComunRoadmapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("planned", "Планируется"),
                            ("in_progress", "В работе"),
                            ("done", "Сделано"),
                        ],
                        default="planned",
                        max_length=24,
                        verbose_name="Столбец",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0, verbose_name="Позиция")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_comun_roadmap_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Добавил",
                    ),
                ),
                (
                    "comun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_items",
                        to="feeds.comun",
                        verbose_name="Сообщество",
                    ),
                ),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comun_roadmap_item",
                        to="feeds.post",
                        verbose_name="Пост",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент дорожной карты",
                "verbose_name_plural": "Элементы дорожных карт",
                "ordering": ["stage", "position", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["comun", "stage", "position"],
                        name="comroad_comun_stage_pos_idx",
                    ),
                ],
            },
        ),
    ]
