# Generated by Codex on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0168_comun_roadmap_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="original_language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "Английский"),
                    ("es", "Испанский"),
                    ("pt", "Португальский"),
                    ("de", "Немецкий"),
                    ("fr", "Французский"),
                    ("tr", "Турецкий"),
                    ("id", "Индонезийский"),
                ],
                db_index=True,
                default="ru",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="posttranslation",
            name="language",
            field=models.CharField(
                choices=[
                    ("ru", "Русский"),
                    ("en", "Английский"),
                    ("es", "Испанский"),
                    ("pt", "Португальский"),
                    ("de", "Немецкий"),
                    ("fr", "Французский"),
                    ("tr", "Турецкий"),
                    ("id", "Индонезийский"),
                ],
                db_index=True,
                max_length=8,
            ),
        ),
    ]
