# Generated by Django 5.2.9 on 2026-08-19 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_event_template(apps, schema_editor):
    PostTemplateConfig = apps.get_model("feeds", "PostTemplateConfig")
    basic = PostTemplateConfig.objects.filter(template_type="basic").first()
    enabled_blocks = list(
        getattr(basic, "enabled_editor_blocks", [])
        or [
            "header",
            "toc",
            "list",
            "table",
            "image",
            "quote",
            "callout",
            "author",
            "code",
            "poll",
            "divider",
            "spoiler",
            "gallery",
            "map",
            "compare",
            "link",
            "embed",
            "post_link",
            "music",
            "movie_time",
            "post_rating",
        ]
    )
    PostTemplateConfig.objects.update_or_create(
        template_type="event",
        defaults={
            "label": "Событие",
            "description": "Пост с датой события, календарем и напоминанием участникам.",
            "enabled_editor_blocks": enabled_blocks,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0172_post_question_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='PostEventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to='feeds.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reminder_sent_at', 'post'], name='event_attendance_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'user'), name='feeds_post_event_attendance_unique')],
            },
        ),
        migrations.RunPython(ensure_event_template, migrations.RunPython.noop),
    ]
