# Generated by Django 5.2.9 on 2026-09-17 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def register_template(apps, schema_editor):
    Config = apps.get_model("feeds", "PostTemplateConfig")
    basic = Config.objects.filter(template_type="basic").first()
    Config.objects.get_or_create(template_type="companion", defaults={
        "label": "Поиск спутника", "description": "Место и время встречи, отклики и выбор одного участника.",
        "enabled_editor_blocks": getattr(basic, "enabled_editor_blocks", []) or ["header", "list", "image", "map"],
        "is_active": True,
    })


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0175_comun_telegram_ai_summary_prompt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(register_template, migrations.RunPython.noop),
        migrations.AddField(
            model_name='post',
            name='companion_matched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sitechatmessage',
            name='event',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CompanionSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_searches', to='feeds.sitechat')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_searches', to=settings.AUTH_USER_MODEL)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companion_search', to='feeds.post')),
                ('selected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_responses', to=settings.AUTH_USER_MODEL)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feeds.companionsearch')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('search', 'user'), name='companion_response_unique')],
            },
        ),
    ]
