# Generated by Django 5.2.9 on 2026-10-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0180_mention_community_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuserprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
