# Generated by Django 5.2.9 on 2026-09-21 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0176_companion_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user_id', models.BigIntegerField(unique=True)),
                ('dialog_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_events', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='max_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaxChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('chat_type', models.CharField(max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_publish', models.BooleanField(default=True)),
                ('publish_delay_days', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.author')),
                ('comun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_chats', to='feeds.comun')),
                ('verified_users', models.ManyToManyField(related_name='verified_max_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaxUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['processed_at', 'available_at'], name='max_integra_process_cd6597_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaxVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaxImportedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='max_integration.maxchat')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feeds.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chat', 'message_id'), name='max_imported_message_unique')],
            },
        ),
        migrations.CreateModel(
            name='MaxNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='max_integration.maxaccount')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.sitenotification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'notification'), name='max_notification_unique')],
            },
        ),
    ]
