# Generated by Django 5.2.9 on 2026-09-21 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0176_companion_search'),
        ('max_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('kb', 'База знаний'), ('glossary', 'Глоссарий')], max_length=16)),
                ('source_text', models.TextField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='max_integration.maxchat')),
                ('comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_submissions', to='feeds.comun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chat', 'comun', 'message_id', 'request_type'), name='max_submission_unique')],
            },
        ),
    ]
