# Generated by Django 5.2.9 on 2026-05-08 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialProjectGeneratedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.SlugField(default='landname', max_length=80)),
                ('text', models.CharField(max_length=64)),
                ('share_query', models.CharField(max_length=64)),
                ('was_shared', models.BooleanField(default=False)),
                ('share_clicks', models.PositiveIntegerField(default=0)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_project_generated_phrases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сгенерированная фраза спецпроекта',
                'verbose_name_plural': 'Сгенерированные фразы спецпроекта',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['project_slug', 'created_at'], name='special_pro_project_230d59_idx'), models.Index(fields=['project_slug', 'was_shared', 'created_at'], name='special_pro_project_50918f_idx'), models.Index(fields=['project_slug', 'text'], name='special_pro_project_dbd2d4_idx')],
            },
        ),
    ]
