# Generated by Django 5.2.9 on 2026-05-17 12:04

import django.db.models.deletion
import django.utils.timezone
import special_projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_projects', '0002_specialprojectgeneratedphrase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmJourneyFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.SlugField(default='1001-films', max_length=80)),
                ('title', models.CharField(max_length=220)),
                ('original_title', models.CharField(blank=True, max_length=220)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('imdb_url', models.URLField(blank=True, max_length=700)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=700)),
                ('runtime_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=220)),
                ('country', models.CharField(blank=True, max_length=160)),
                ('genres', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фильм спецпроекта 1001',
                'verbose_name_plural': 'Фильмы спецпроекта 1001',
                'ordering': ('project_slug', 'sort_order', 'id'),
                'indexes': [models.Index(fields=['project_slug', 'is_active', 'sort_order'], name='special_pro_project_30c7ed_idx'), models.Index(fields=['project_slug', 'title'], name='special_pro_project_258d28_idx'), models.Index(fields=['project_slug', 'original_title'], name='special_pro_project_c5bb7c_idx')],
                'constraints': [models.UniqueConstraint(fields=('project_slug', 'sort_order'), name='special_projects_film_journey_unique_order')],
            },
        ),
        migrations.CreateModel(
            name='FilmJourneySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.SlugField(default='1001-films', max_length=80)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('paused', 'Пауза'), ('completed', 'Завершена')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_delivery_at', models.DateTimeField()),
                ('last_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('pause_reason', models.CharField(blank=True, max_length=160)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_journey_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на спецпроект 1001',
                'verbose_name_plural': 'Подписки на спецпроект 1001',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FilmJourneyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('access_token', models.CharField(default=special_projects.models.film_journey_access_token, max_length=96, unique=True)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('second_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journey_entries', to='special_projects.filmjourneyfilm')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='special_projects.filmjourneysubscription')),
            ],
            options={
                'verbose_name': 'Выдача фильма спецпроекта 1001',
                'verbose_name_plural': 'Выдачи фильмов спецпроекта 1001',
                'ordering': ('subscription', 'position'),
            },
        ),
        migrations.AddIndex(
            model_name='filmjourneysubscription',
            index=models.Index(fields=['project_slug', 'status', 'next_delivery_at'], name='special_pro_project_b8f619_idx'),
        ),
        migrations.AddIndex(
            model_name='filmjourneysubscription',
            index=models.Index(fields=['user', 'status'], name='special_pro_user_id_90267e_idx'),
        ),
        migrations.AddConstraint(
            model_name='filmjourneysubscription',
            constraint=models.UniqueConstraint(fields=('project_slug', 'user'), name='special_projects_film_journey_unique_user'),
        ),
        migrations.AddIndex(
            model_name='filmjourneyentry',
            index=models.Index(fields=['access_token'], name='special_pro_access__7977e1_idx'),
        ),
        migrations.AddIndex(
            model_name='filmjourneyentry',
            index=models.Index(fields=['subscription', 'completed_at'], name='special_pro_subscri_7df329_idx'),
        ),
        migrations.AddIndex(
            model_name='filmjourneyentry',
            index=models.Index(fields=['available_at', 'notification_sent_at'], name='special_pro_availab_0847eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='filmjourneyentry',
            constraint=models.UniqueConstraint(fields=('subscription', 'position'), name='special_projects_film_journey_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='filmjourneyentry',
            constraint=models.UniqueConstraint(fields=('subscription', 'film'), name='special_projects_film_journey_unique_film'),
        ),
    ]
