# Generated by Django 5.2.9 on 2026-05-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('special_projects', '0004_seed_1001_films'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmjourneyentry',
            options={'ordering': ('subscription', 'position'), 'verbose_name': 'Выдача фильма спецпроекта 365', 'verbose_name_plural': 'Выдачи фильмов спецпроекта 365'},
        ),
        migrations.AlterModelOptions(
            name='filmjourneyfilm',
            options={'ordering': ('project_slug', 'sort_order', 'id'), 'verbose_name': 'Фильм спецпроекта 365', 'verbose_name_plural': 'Фильмы спецпроекта 365'},
        ),
        migrations.AlterModelOptions(
            name='filmjourneysubscription',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Подписка на спецпроект 365', 'verbose_name_plural': 'Подписки на спецпроект 365'},
        ),
    ]
