# Generated by Codex on 2026-05-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("special_projects", "0005_rename_film_journey_to_365"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicBookState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_slug", models.SlugField(default="book", max_length=80, unique=True)),
                ("total_words", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Состояние книги спецпроекта",
                "verbose_name_plural": "Состояния книги спецпроекта",
            },
        ),
        migrations.CreateModel(
            name="PublicBookBlockedWord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_slug", models.SlugField(default="book", max_length=80)),
                ("word", models.CharField(max_length=64)),
                ("normalized_word", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_book_blocked_words",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрещенное слово книги",
                "verbose_name_plural": "Запрещенные слова книги",
                "ordering": ("project_slug", "normalized_word"),
            },
        ),
        migrations.CreateModel(
            name="PublicBookWord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_slug", models.SlugField(default="book", max_length=80)),
                ("position", models.PositiveIntegerField()),
                ("word", models.CharField(max_length=64)),
                ("normalized_word", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_book_words",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Слово книги спецпроекта",
                "verbose_name_plural": "Слова книги спецпроекта",
                "ordering": ("project_slug", "position"),
            },
        ),
        migrations.AddIndex(
            model_name="publicbookblockedword",
            index=models.Index(fields=["project_slug", "is_active", "normalized_word"], name="special_pro_project_742576_idx"),
        ),
        migrations.AddIndex(
            model_name="publicbookword",
            index=models.Index(fields=["project_slug", "position"], name="special_pro_project_d85ee9_idx"),
        ),
        migrations.AddIndex(
            model_name="publicbookword",
            index=models.Index(fields=["project_slug", "created_at"], name="special_pro_project_9514ad_idx"),
        ),
        migrations.AddIndex(
            model_name="publicbookword",
            index=models.Index(fields=["submitted_by", "created_at"], name="special_pro_submitt_504389_idx"),
        ),
        migrations.AddIndex(
            model_name="publicbookword",
            index=models.Index(fields=["project_slug", "normalized_word"], name="special_pro_project_7c4732_idx"),
        ),
        migrations.AddConstraint(
            model_name="publicbookblockedword",
            constraint=models.UniqueConstraint(
                fields=("project_slug", "normalized_word"),
                name="special_projects_public_book_unique_blocked_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicbookword",
            constraint=models.UniqueConstraint(
                fields=("project_slug", "position"),
                name="special_projects_public_book_unique_position",
            ),
        ),
    ]
