# Generated by Django 5.2.9 on 2026-05-20 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_projects', '0006_public_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicbookstate',
            options={'verbose_name': 'Состояние книги сообщества', 'verbose_name_plural': 'Состояния книги сообщества'},
        ),
        migrations.AlterModelOptions(
            name='publicbookword',
            options={'ordering': ('project_slug', 'position'), 'verbose_name': 'Слово книги сообщества', 'verbose_name_plural': 'Слова книги сообщества'},
        ),
        migrations.CreateModel(
            name='PublicBookReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.SlugField(default='book', max_length=80)),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_book_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Напоминание книги сообщества',
                'verbose_name_plural': 'Напоминания книги сообщества',
                'ordering': ('scheduled_at', 'id'),
                'indexes': [models.Index(fields=['project_slug', 'sent_at', 'scheduled_at'], name='special_pro_project_6dc980_idx'), models.Index(fields=['user', 'sent_at', 'scheduled_at'], name='special_pro_user_id_6147c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('project_slug', 'user', 'scheduled_at'), name='special_projects_public_book_unique_reminder')],
            },
        ),
    ]
