# Generated by Django 5.2.9 on 2026-05-20 06:13

import django.db.models.deletion
import special_projects.models
from django.conf import settings
from django.db import migrations, models


def truncate_public_book_words(apps, schema_editor):
    PublicBookWord = apps.get_model("special_projects", "PublicBookWord")
    for item in PublicBookWord.objects.all().iterator():
        updates = []
        if item.word and len(item.word) > 30:
            item.word = item.word[:30]
            updates.append("word")
        if item.normalized_word and len(item.normalized_word) > 30:
            item.normalized_word = item.normalized_word[:30]
            updates.append("normalized_word")
        if updates:
            item.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('special_projects', '0007_publicbookreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(truncate_public_book_words, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='publicbookword',
            name='normalized_word',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='publicbookword',
            name='word',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='PublicBookProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.SlugField(default='book', max_length=80, unique=True)),
                ('rules_text', models.TextField(blank=True)),
                ('final_pdf', models.FileField(blank=True, upload_to=special_projects.models.public_book_final_pdf_path)),
                ('final_pdf_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('final_pdf_announced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_public_book_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки книги сообщества',
                'verbose_name_plural': 'Настройки книги сообщества',
            },
        ),
        migrations.CreateModel(
            name='PublicBookFinalNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.SlugField(default='book', max_length=80)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_book_final_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на финальную книгу',
                'verbose_name_plural': 'Подписки на финальную книгу',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['project_slug', 'notified_at', 'created_at'], name='special_pro_project_f84fc5_idx'), models.Index(fields=['user', 'created_at'], name='special_pro_user_id_3c55e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('project_slug', 'user'), name='special_projects_public_book_unique_final_subscription')],
            },
        ),
    ]
