# Generated by Django 5.2.9 on 2026-05-20 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_projects', '0008_alter_publicbookword_normalized_word_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBookModerationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_slug', models.SlugField(default='book', max_length=80)),
                ('consecutive_violations', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние модерации книги',
                'verbose_name_plural': 'Состояния модерации книги',
                'ordering': ('project_slug', 'user_id'),
            },
        ),
        migrations.AddField(
            model_name='publicbookword',
            name='censored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicbookword',
            name='censored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='censored_public_book_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicbookword',
            name='is_censored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='publicbookword',
            index=models.Index(fields=['project_slug', 'is_censored'], name='special_pro_project_38269d_idx'),
        ),
        migrations.AddField(
            model_name='publicbookmoderationstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_book_moderation_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='publicbookmoderationstate',
            index=models.Index(fields=['project_slug', 'locked_until'], name='special_pro_project_4f8547_idx'),
        ),
        migrations.AddIndex(
            model_name='publicbookmoderationstate',
            index=models.Index(fields=['user', 'locked_until'], name='special_pro_user_id_b6fb0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicbookmoderationstate',
            constraint=models.UniqueConstraint(fields=('project_slug', 'user'), name='special_projects_public_book_unique_moderation_user'),
        ),
    ]
