# Generated by Codex on 2026-05-22

from datetime import timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Max


def migrate_public_book_submission_states(apps, schema_editor):
    PublicBookWord = apps.get_model("special_projects", "PublicBookWord")
    PublicBookSubmissionState = apps.get_model("special_projects", "PublicBookSubmissionState")

    rows = (
        PublicBookWord.objects.exclude(submitted_by_id__isnull=True)
        .values("project_slug", "submitted_by_id")
        .annotate(words_count=Count("id"), last_created_at=Max("created_at"))
    )
    for row in rows.iterator():
        last_created_at = row["last_created_at"]
        PublicBookSubmissionState.objects.update_or_create(
            project_slug=row["project_slug"],
            user_id=row["submitted_by_id"],
            defaults={
                "words_count": int(row["words_count"] or 0),
                "next_available_at": last_created_at + timedelta(hours=24)
                if last_created_at
                else None,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("special_projects", "0010_seed_public_book_stop_words"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicBookSubmissionState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_slug", models.SlugField(default="book", max_length=80)),
                ("words_count", models.PositiveIntegerField(default=0)),
                ("next_available_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_book_submission_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние отправок в книгу",
                "verbose_name_plural": "Состояния отправок в книгу",
                "ordering": ("project_slug", "user_id"),
            },
        ),
        migrations.AddIndex(
            model_name="publicbooksubmissionstate",
            index=models.Index(fields=["project_slug", "next_available_at"], name="special_pro_project_87e220_idx"),
        ),
        migrations.AddIndex(
            model_name="publicbooksubmissionstate",
            index=models.Index(fields=["user", "next_available_at"], name="special_pro_user_id_5f8f3e_idx"),
        ),
        migrations.AddIndex(
            model_name="publicbooksubmissionstate",
            index=models.Index(fields=["project_slug", "words_count"], name="special_pro_project_8cda70_idx"),
        ),
        migrations.AddConstraint(
            model_name="publicbooksubmissionstate",
            constraint=models.UniqueConstraint(
                fields=("project_slug", "user"),
                name="special_projects_public_book_unique_submission_state",
            ),
        ),
        migrations.RunPython(migrate_public_book_submission_states, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="publicbookword",
            name="special_pro_project_9514ad_idx",
        ),
        migrations.RemoveIndex(
            model_name="publicbookword",
            name="special_pro_submitt_504389_idx",
        ),
        migrations.RemoveField(
            model_name="publicbookword",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="publicbookword",
            name="submitted_by",
        ),
    ]
