# Generated by Codex on 2026-05-28

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def migrate_public_book_reminders_to_recurring(apps, schema_editor):
    PublicBookReminder = apps.get_model("special_projects", "PublicBookReminder")
    PublicBookSubmissionState = apps.get_model("special_projects", "PublicBookSubmissionState")

    current = timezone.now()
    subscriptions = PublicBookReminder.objects.values("project_slug", "user_id").distinct()
    for subscription in subscriptions.iterator():
        project_slug = subscription["project_slug"]
        user_id = subscription["user_id"]
        if PublicBookReminder.objects.filter(
            project_slug=project_slug,
            user_id=user_id,
            sent_at__isnull=True,
        ).exists():
            continue

        next_available_at = (
            PublicBookSubmissionState.objects.filter(project_slug=project_slug, user_id=user_id)
            .values_list("next_available_at", flat=True)
            .first()
        )
        latest_sent_at = (
            PublicBookReminder.objects.filter(
                project_slug=project_slug,
                user_id=user_id,
                sent_at__isnull=False,
            )
            .order_by("-sent_at", "-scheduled_at", "-id")
            .values_list("sent_at", flat=True)
            .first()
        )

        if next_available_at and next_available_at > current:
            scheduled_at = next_available_at
        elif latest_sent_at:
            scheduled_at = max(latest_sent_at + timedelta(hours=24), current)
        elif next_available_at:
            scheduled_at = max(next_available_at, current)
        else:
            scheduled_at = current

        PublicBookReminder.objects.update_or_create(
            project_slug=project_slug,
            user_id=user_id,
            scheduled_at=scheduled_at,
            defaults={"sent_at": None},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("special_projects", "0011_anonymize_public_book_words"),
    ]

    operations = [
        migrations.RunPython(migrate_public_book_reminders_to_recurring, migrations.RunPython.noop),
    ]
