# Generated by Codex on 2026-05-28

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def limit_public_book_reminder_cycles(apps, schema_editor):
    PublicBookReminder = apps.get_model("special_projects", "PublicBookReminder")
    PublicBookSubmissionState = apps.get_model("special_projects", "PublicBookSubmissionState")

    current = timezone.now()
    interval = timedelta(hours=24)
    subscriptions = PublicBookReminder.objects.values("project_slug", "user_id").distinct()
    for subscription in subscriptions.iterator():
        project_slug = subscription["project_slug"]
        user_id = subscription["user_id"]
        reminder_qs = PublicBookReminder.objects.filter(
            project_slug=project_slug,
            user_id=user_id,
        )
        pending_qs = reminder_qs.filter(sent_at__isnull=True)
        next_available_at = (
            PublicBookSubmissionState.objects.filter(
                project_slug=project_slug,
                user_id=user_id,
            )
            .values_list("next_available_at", flat=True)
            .first()
        )

        pending_qs.delete()
        if not next_available_at:
            continue

        sent_count = reminder_qs.filter(
            scheduled_at__gte=next_available_at,
            sent_at__isnull=False,
        ).count()
        if sent_count >= 2:
            continue

        if sent_count <= 0:
            scheduled_at = next_available_at if next_available_at > current else current
        else:
            latest_sent_at = (
                reminder_qs.filter(sent_at__isnull=False)
                .order_by("-sent_at", "-scheduled_at", "-id")
                .values_list("sent_at", flat=True)
                .first()
            )
            scheduled_at = latest_sent_at + interval if latest_sent_at else current + interval
            scheduled_at = scheduled_at if scheduled_at > current else current

        for _attempt in range(10):
            if not reminder_qs.filter(scheduled_at=scheduled_at).exists():
                PublicBookReminder.objects.create(
                    project_slug=project_slug,
                    user_id=user_id,
                    scheduled_at=scheduled_at,
                )
                break
            scheduled_at = scheduled_at + timedelta(microseconds=1)


class Migration(migrations.Migration):

    dependencies = [
        ("special_projects", "0012_public_book_recurring_reminders"),
    ]

    operations = [
        migrations.RunPython(limit_public_book_reminder_cycles, migrations.RunPython.noop),
    ]
