# Generated by Django 5.2.9 on 2026-09-10 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('key_prefix', models.CharField(editable=False, max_length=16, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('allowed_community_slugs', models.JSONField(blank=True, default=list)),
                ('allowed_ip_networks', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ключ API аналитики',
                'verbose_name_plural': 'Ключи API аналитики',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AnalyticsApiAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=80)),
                ('community_slug', models.SlugField(blank=True, max_length=160)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='product_analytics.analyticsapicredential')),
            ],
            options={
                'verbose_name': 'Обращение к API аналитики',
                'verbose_name_plural': 'Обращения к API аналитики',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['credential', '-created_at'], name='analytics_key_access_idx'), models.Index(fields=['endpoint', '-created_at'], name='analytics_endpoint_idx')],
            },
        ),
    ]
