import type { RequestHandler } from './$types'

export const GET: RequestHandler = ({ url }) => {
  const origin = url.origin.replace(/\/+$/, '')
  const body = [
    'User-agent: TikTokSpider',
    'Crawl-delay: 10',
    'Disallow:',
    '',
    'User-agent: Bytespider',
    'Crawl-delay: 10',
    'Disallow:',
    '',
    'User-agent: AhrefsBot',
    'Disallow: /',
    '',
    'User-agent: AhrefsSiteAudit',
    'Disallow: /',
    '',
    'User-agent: SemrushBot',
    'Disallow: /',
    '',
    'User-agent: SemrushBot-BA',
    'Disallow: /',
    '',
    'User-agent: SemrushBot-SI',
    'Disallow: /',
    '',
    'User-agent: SemrushBot-SWA',
    'Disallow: /',
    '',
    'User-agent: SemrushBot-OCOB',
    'Disallow: /',
    '',
    'User-agent: SemrushBot-FT',
    'Disallow: /',
    '',
    'User-agent: SemrushBot-ESI',
    'Disallow: /',
    '',
    'User-agent: SiteAuditBot',
    'Disallow: /',
    '',
    'User-agent: SplitSignalBot',
    'Disallow: /',
    '',
    'User-agent: RyteBot',
    'Disallow: /',
    '',
    'User-agent: Amazonbot',
    'Disallow: /',
    '',
    'User-agent: SERankingBacklinksBot',
    'Disallow: /',
    '',
    'User-agent: DotBot',
    'Disallow: /',
    '',
    'User-agent: Sogou web spider',
    'Disallow: /',
    '',
    'User-agent: Sogou inst spider',
    'Disallow: /',
    '',
    'User-agent: Sogou spider2',
    'Disallow: /',
    '',
    'User-agent: Sogou Pic Spider',
    'Disallow: /',
    '',
    'User-agent: Baiduspider',
    'Disallow: /',
    '',
    'User-agent: *',
    'Disallow: /admin/',
    'Disallow: /settings/',
    'Disallow: /accounts/',
    'Disallow: /inbox/',
    'Disallow: /inbox/messages/',
    'Disallow: /*?thread=',
    '',
    `Host: ${origin.replace(/^https?:\/\//, '')}`,
    `Sitemap: ${origin}/sitemap.xml`,
    '',
  ].join('\n')

  return new Response(body, {
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'cache-control': 'public, max-age=3600',
    },
  })
}
