from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from feeds.views import (
    auth_me,
    author_verification_code,
    author_posts,
    comment_detail,
    comment_like,
    fresh_feed,
    home_feed,
    login_user,
    my_feed,
    post_detail,
    post_comments,
    post_like,
    post_read,
    recent_comments,
    register_user,
    rubric_posts,
    rubrics_list,
    search_content,
    sitemap_authors_xml,
    sitemap_posts_xml,
    sitemap_rubrics_xml,
    sitemap_static_xml,
    sitemap_xml,
    tags_list,
    tag_posts,
    telegram_auth,
    telegram_webhook,
    top_authors_month,
    user_post_update,
    user_posts,
    user_upload,
    vk_auth,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/authors/<str:username>/posts/", author_posts, name="author-posts"),
    path("api/rubrics/", rubrics_list, name="rubrics-list"),
    path("api/rubrics/<str:slug>/posts/", rubric_posts, name="rubric-posts"),
    path("api/tags/", tags_list, name="tag-list"),
    path("api/tags/<str:tag>/posts/", tag_posts, name="tag-posts"),
    path("api/posts/<int:post_id>/", post_detail, name="post-detail"),
    path("api/posts/<int:post_id>/comments/", post_comments, name="post-comments"),
    path("api/posts/<int:post_id>/like/", post_like, name="post-like"),
    path("api/posts/<int:post_id>/read/", post_read, name="post-read"),
    path("api/comments/<int:comment_id>/", comment_detail, name="comment-detail"),
    path("api/comments/<int:comment_id>/like/", comment_like, name="comment-like"),
    path("api/comments/recent/", recent_comments, name="recent-comments"),
    path("api/home/", home_feed, name="home-feed"),
    path("api/home/fresh/", fresh_feed, name="fresh-feed"),
    path("api/home/my/", my_feed, name="my-feed"),
    path("api/search/", search_content, name="search-content"),
    path("api/authors/top-month/", top_authors_month, name="top-authors-month"),
    path("api/auth/register/", register_user, name="auth-register"),
    path("api/auth/login/", login_user, name="auth-login"),
    path("api/auth/telegram/", telegram_auth, name="auth-telegram"),
    path("api/auth/vk/", vk_auth, name="auth-vk"),
    path("api/auth/me/", auth_me, name="auth-me"),
    path("api/auth/verification-code/", author_verification_code, name="auth-verification-code"),
    path("api/auth/posts/", user_posts, name="auth-posts"),
    path("api/auth/posts/<int:post_id>/", user_post_update, name="auth-post-update"),
    path("api/auth/uploads/", user_upload, name="auth-uploads"),
    path("sitemap.xml", sitemap_xml, name="sitemap-xml"),
    path("sitemap-static.xml", sitemap_static_xml, name="sitemap-static-xml"),
    path("sitemap-rubrics.xml", sitemap_rubrics_xml, name="sitemap-rubrics-xml"),
    path("sitemap-authors.xml", sitemap_authors_xml, name="sitemap-authors-xml"),
    path("sitemap-posts-<int:page>.xml", sitemap_posts_xml, name="sitemap-posts-xml"),
    path("tg/webhook/<str:token>/", telegram_webhook, name="telegram-webhook"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
