from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from communities.views import (
    comun_create_from_telegram_channel,
    comun_detail_manage,
    comun_knowledge_base,
    comun_knowledge_base_item,
    comun_post_category_update,
    comun_posts,
    comun_vote,
    comuns_composer,
    comuns_list_create,
    comuns_sidebar,
)
from editor.views import (
    auth_movie_review_autofill,
    bug_report_confirmation_update,
    bug_report_status_update,
    post_poll_vote,
    post_rating_vote,
    shared_draft_detail,
    user_post_update,
    user_posts,
    user_upload,
)
from feeds.views import (
    author_posts,
    comment_detail,
    comment_like,
    content_page_manage,
    favorites_feed,
    home_feed,
    post_detail,
    post_comments,
    post_favorite,
    post_like,
    post_read,
    post_view,
    recent_comments,
    search_content,
    sitemap_authors_xml,
    sitemap_posts_xml,
    sitemap_static_xml,
    sitemap_xml,
    tags_ensure,
    tags_list,
    tag_posts,
)
from feeds.wherefilmed_import import wherefilmed_import
from landing_pages.views import (
    admin_landing_page_detail,
    admin_landing_page_image_detail,
    admin_landing_page_images,
    admin_landing_pages,
    landing_page_detail,
    landing_page_leads,
)
from my_feed.views import (
    auth_feed_settings,
    my_feed,
)
from moderator.views import (
    moderator_analytics,
    moderator_post_view_setting_update,
    moderator_post_view_settings,
    moderator_rating_settings,
    moderator_rating_settings_update,
)
from notifications.views import (
    auth_notification_read,
    auth_notification_push_devices,
    auth_notification_settings,
    auth_notifications,
    auth_notifications_read_all,
)
from ratings.views import top_authors, top_authors_month, top_comuns, top_comuns_month
from special_projects.views import (
    film_journey_admin_film_detail,
    film_journey_admin_films,
    film_journey_admin_landing_images,
    film_journey_entry_comments,
    film_journey_entry_detail,
    film_journey_entry_rating_vote,
    film_journey_resume,
    film_journey_start,
    film_journey_status,
    landname_admin_generations,
    landname_admin_letter_detail,
    landname_admin_letters,
    landname_admin_suggestion_approve,
    landname_admin_suggestion_detail,
    landname_alphabet,
    landname_preview_image,
    landname_render,
    landname_share_event,
    landname_suggestions,
    landname_tile,
    public_book_admin_blocked_word_detail,
    public_book_admin_blocked_words,
    public_book_admin_settings,
    public_book_admin_selection_censor,
    public_book_final_notification,
    public_book_reminder,
    public_book_admin_stats,
    public_book_admin_word_censor,
    public_book_admin_words,
    public_book_status,
    public_book_submit,
    public_book_words,
)
from telegram_integration.views import telegram_auth, telegram_webhook
from users.views import (
    auth_me,
    author_verification_code,
    login_user,
    logout_user,
    password_reset_confirm,
    password_reset_request,
    public_user_profile,
    register_user,
    verify_email,
    vk_auth,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/authors/<str:username>/posts/", author_posts, name="author-posts"),
    path("api/tags/", tags_list, name="tag-list"),
    path("api/tags/ensure/", tags_ensure, name="tag-ensure"),
    path("api/tags/<str:tag>/posts/", tag_posts, name="tag-posts"),
    path("api/posts/<int:post_id>/", post_detail, name="post-detail"),
    path("api/posts/<int:post_id>/comments/", post_comments, name="post-comments"),
    path("api/posts/<int:post_id>/favorite/", post_favorite, name="post-favorite"),
    path("api/posts/<int:post_id>/like/", post_like, name="post-like"),
    path("api/posts/<int:post_id>/poll-vote/", post_poll_vote, name="post-poll-vote"),
    path("api/posts/<int:post_id>/rating-vote/", post_rating_vote, name="post-rating-vote"),
    path(
        "api/posts/<int:post_id>/bug-report-status/",
        bug_report_status_update,
        name="post-bug-report-status",
    ),
    path(
        "api/posts/<int:post_id>/bug-report-confirmation/",
        bug_report_confirmation_update,
        name="post-bug-report-confirmation",
    ),
    path("api/posts/<int:post_id>/read/", post_read, name="post-read"),
    path("api/posts/<int:post_id>/view/", post_view, name="post-view"),
    path("api/comments/<int:comment_id>/", comment_detail, name="comment-detail"),
    path("api/comments/<int:comment_id>/like/", comment_like, name="comment-like"),
    path("api/comments/recent/", recent_comments, name="recent-comments"),
    path("api/content-pages/<slug:slug>/", content_page_manage, name="content-page-manage"),
    path("api/home/", home_feed, name="home-feed"),
    path("api/home/favorites/", favorites_feed, name="favorites-feed"),
    path("api/home/my/", my_feed, name="my-feed"),
    path("api/comuns/", comuns_list_create, name="comuns-list-create"),
    path("api/comuns/composer/", comuns_composer, name="comuns-composer"),
    path("api/comuns/sidebar/", comuns_sidebar, name="comuns-sidebar"),
    path(
        "api/comuns/from-telegram-channel/",
        comun_create_from_telegram_channel,
        name="comun-create-from-telegram-channel",
    ),
    path("api/comuns/top/", top_comuns, name="top-comuns"),
    path("api/comuns/top-month/", top_comuns_month, name="top-comuns-month"),
    path(
        "api/comuns/<slug:slug>/knowledge-base/",
        comun_knowledge_base,
        name="comun-knowledge-base",
    ),
    path(
        "api/comuns/<slug:slug>/knowledge-base/<int:item_id>/",
        comun_knowledge_base_item,
        name="comun-knowledge-base-item",
    ),
    path("api/comuns/<slug:slug>/", comun_detail_manage, name="comun-detail-manage"),
    path("api/comuns/<slug:slug>/vote/", comun_vote, name="comun-vote"),
    path("api/comuns/<slug:slug>/posts/", comun_posts, name="comun-posts"),
    path(
        "api/comuns/<slug:slug>/posts/<int:post_id>/category/",
        comun_post_category_update,
        name="comun-post-category-update",
    ),
    path("api/search/", search_content, name="search-content"),
    path("api/wherefilmed/import/", wherefilmed_import, name="wherefilmed-import"),
    path("api/landing-pages/<slug:slug>/", landing_page_detail, name="landing-page-detail"),
    path("api/landing-pages/<slug:slug>/leads/", landing_page_leads, name="landing-page-leads"),
    path("api/landing-pages/admin/pages/", admin_landing_pages, name="landing-pages-admin-pages"),
    path(
        "api/landing-pages/admin/pages/<slug:slug>/",
        admin_landing_page_detail,
        name="landing-pages-admin-page-detail",
    ),
    path(
        "api/landing-pages/admin/pages/<slug:slug>/images/",
        admin_landing_page_images,
        name="landing-pages-admin-page-images",
    ),
    path(
        "api/landing-pages/admin/images/<int:image_id>/",
        admin_landing_page_image_detail,
        name="landing-pages-admin-image-detail",
    ),
    path("api/authors/top/", top_authors, name="top-authors"),
    path("api/authors/top-month/", top_authors_month, name="top-authors-month"),
    path("api/auth/register/", register_user, name="auth-register"),
    path("api/auth/login/", login_user, name="auth-login"),
    path("api/auth/logout/", logout_user, name="auth-logout"),
    path("api/auth/password-reset/", password_reset_request, name="auth-password-reset"),
    path("api/auth/verify-email/", verify_email, name="auth-verify-email"),
    path(
        "api/auth/password-reset/confirm/",
        password_reset_confirm,
        name="auth-password-reset-confirm",
    ),
    path("api/auth/telegram/", telegram_auth, name="auth-telegram"),
    path("api/auth/vk/", vk_auth, name="auth-vk"),
    path("api/auth/me/", auth_me, name="auth-me"),
    path("api/auth/feed-settings/", auth_feed_settings, name="auth-feed-settings"),
    path(
        "api/auth/post-templates/movie-review/autofill/",
        auth_movie_review_autofill,
        name="auth-movie-review-autofill",
    ),
    path("api/auth/notifications/", auth_notifications, name="auth-notifications"),
    path(
        "api/auth/notifications/settings/",
        auth_notification_settings,
        name="auth-notification-settings",
    ),
    path(
        "api/auth/notifications/push-devices/",
        auth_notification_push_devices,
        name="auth-notification-push-devices",
    ),
    path(
        "api/auth/notifications/read-all/",
        auth_notifications_read_all,
        name="auth-notifications-read-all",
    ),
    path(
        "api/auth/notifications/<int:notification_id>/read/",
        auth_notification_read,
        name="auth-notification-read",
    ),
    path("api/site-users/<int:user_id>/profile/", public_user_profile, name="public-user-profile"),
    path("api/auth/verification-code/", author_verification_code, name="auth-verification-code"),
    path("api/auth/posts/", user_posts, name="auth-posts"),
    path("api/moderator/analytics/", moderator_analytics, name="moderator-analytics"),
    path(
        "api/moderator/post-view-settings/",
        moderator_post_view_settings,
        name="moderator-post-view-settings",
    ),
    path(
        "api/moderator/posts/<int:post_id>/view-settings/",
        moderator_post_view_setting_update,
        name="moderator-post-view-setting-update",
    ),
    path(
        "api/moderator/rating-settings/",
        moderator_rating_settings,
        name="moderator-rating-settings",
    ),
    path(
        "api/moderator/rating-settings/update/",
        moderator_rating_settings_update,
        name="moderator-rating-settings-update",
    ),
    path("api/auth/posts/<int:post_id>/", user_post_update, name="auth-post-update"),
    path(
        "api/auth/drafts/shared/<str:share_token>/",
        shared_draft_detail,
        name="auth-shared-draft-detail",
    ),
    path("api/auth/uploads/", user_upload, name="auth-uploads"),
    path("api/special-projects/landname/", landname_render, name="special-landname-render"),
    path(
        "api/special-projects/landname/share/",
        landname_share_event,
        name="special-landname-share-event",
    ),
    path(
        "api/special-projects/landname/preview.png",
        landname_preview_image,
        name="special-landname-preview-image",
    ),
    path(
        "api/special-projects/landname/alphabet/",
        landname_alphabet,
        name="special-landname-alphabet",
    ),
    path(
        "api/special-projects/landname/suggestions/",
        landname_suggestions,
        name="special-landname-suggestions",
    ),
    path(
        "api/special-projects/landname/admin/letters/",
        landname_admin_letters,
        name="special-landname-admin-letters",
    ),
    path(
        "api/special-projects/landname/admin/generations/",
        landname_admin_generations,
        name="special-landname-admin-generations",
    ),
    path(
        "api/special-projects/landname/admin/letters/<int:image_id>/",
        landname_admin_letter_detail,
        name="special-landname-admin-letter-detail",
    ),
    path(
        "api/special-projects/landname/admin/suggestions/<int:suggestion_id>/",
        landname_admin_suggestion_detail,
        name="special-landname-admin-suggestion-detail",
    ),
    path(
        "api/special-projects/landname/admin/suggestions/<int:suggestion_id>/approve/",
        landname_admin_suggestion_approve,
        name="special-landname-admin-suggestion-approve",
    ),
    path(
        "api/special-projects/landname/tiles/<str:key>.svg",
        landname_tile,
        name="special-landname-tile",
    ),
    path(
        "api/special-projects/book/status/",
        public_book_status,
        name="special-book-status",
    ),
    path(
        "api/special-projects/book/admin/stats/",
        public_book_admin_stats,
        name="special-book-admin-stats",
    ),
    path(
        "api/special-projects/book/admin/settings/",
        public_book_admin_settings,
        name="special-book-admin-settings",
    ),
    path(
        "api/special-projects/book/admin/blocked-words/",
        public_book_admin_blocked_words,
        name="special-book-admin-blocked-words",
    ),
    path(
        "api/special-projects/book/admin/blocked-words/<int:item_id>/",
        public_book_admin_blocked_word_detail,
        name="special-book-admin-blocked-word-detail",
    ),
    path(
        "api/special-projects/book/admin/words/",
        public_book_admin_words,
        name="special-book-admin-words",
    ),
    path(
        "api/special-projects/book/admin/words/<int:word_id>/censor/",
        public_book_admin_word_censor,
        name="special-book-admin-word-censor",
    ),
    path(
        "api/special-projects/book/admin/selection/censor/",
        public_book_admin_selection_censor,
        name="special-book-admin-selection-censor",
    ),
    path(
        "api/special-projects/book/words/",
        public_book_words,
        name="special-book-words",
    ),
    path(
        "api/special-projects/book/submit/",
        public_book_submit,
        name="special-book-submit",
    ),
    path(
        "api/special-projects/book/reminder/",
        public_book_reminder,
        name="special-book-reminder",
    ),
    path(
        "api/special-projects/book/final-notification/",
        public_book_final_notification,
        name="special-book-final-notification",
    ),
    path(
        "api/special-projects/365-films/status/",
        film_journey_status,
        name="special-365-films-status",
    ),
    path(
        "api/special-projects/365-films/start/",
        film_journey_start,
        name="special-365-films-start",
    ),
    path(
        "api/special-projects/365-films/resume/",
        film_journey_resume,
        name="special-365-films-resume",
    ),
    path(
        "api/special-projects/365-films/entries/<str:access_token>/",
        film_journey_entry_detail,
        name="special-365-films-entry",
    ),
    path(
        "api/special-projects/365-films/entries/<str:access_token>/comments/",
        film_journey_entry_comments,
        name="special-365-films-entry-comments",
    ),
    path(
        "api/special-projects/365-films/entries/<str:access_token>/rating-vote/",
        film_journey_entry_rating_vote,
        name="special-365-films-entry-rating-vote",
    ),
    path(
        "api/special-projects/365-films/admin/films/",
        film_journey_admin_films,
        name="special-365-films-admin-films",
    ),
    path(
        "api/special-projects/365-films/admin/landing-images/",
        film_journey_admin_landing_images,
        name="special-365-films-admin-landing-images",
    ),
    path(
        "api/special-projects/365-films/admin/films/<int:film_id>/",
        film_journey_admin_film_detail,
        name="special-365-films-admin-film-detail",
    ),
    path(
        "api/special-projects/1001-films/status/",
        film_journey_status,
        name="special-1001-films-status",
    ),
    path(
        "api/special-projects/1001-films/start/",
        film_journey_start,
        name="special-1001-films-start",
    ),
    path(
        "api/special-projects/1001-films/resume/",
        film_journey_resume,
        name="special-1001-films-resume",
    ),
    path(
        "api/special-projects/1001-films/entries/<str:access_token>/",
        film_journey_entry_detail,
        name="special-1001-films-entry",
    ),
    path(
        "api/special-projects/1001-films/entries/<str:access_token>/comments/",
        film_journey_entry_comments,
        name="special-1001-films-entry-comments",
    ),
    path(
        "api/special-projects/1001-films/entries/<str:access_token>/rating-vote/",
        film_journey_entry_rating_vote,
        name="special-1001-films-entry-rating-vote",
    ),
    path(
        "api/special-projects/1001-films/admin/films/",
        film_journey_admin_films,
        name="special-1001-films-admin-films",
    ),
    path(
        "api/special-projects/1001-films/admin/landing-images/",
        film_journey_admin_landing_images,
        name="special-1001-films-admin-landing-images",
    ),
    path(
        "api/special-projects/1001-films/admin/films/<int:film_id>/",
        film_journey_admin_film_detail,
        name="special-1001-films-admin-film-detail",
    ),
    path("sitemap.xml", sitemap_xml, name="sitemap-xml"),
    path("sitemap-static.xml", sitemap_static_xml, name="sitemap-static-xml"),
    path("sitemap-authors.xml", sitemap_authors_xml, name="sitemap-authors-xml"),
    path("sitemap-posts-<int:page>.xml", sitemap_posts_xml, name="sitemap-posts-xml"),
    path("tg/webhook/<str:token>/", telegram_webhook, name="telegram-webhook"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
